<a href="https://colab.research.google.com/github/allenbiji/demo/blob/main/ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression



sns.set()

In [ ]:
from google.colab import files

# Upload file
uploaded = files.upload()

# Check the uploaded files
for file_name in uploaded.keys():
    print(f'User uploaded file "{file_name}" with length {len(uploaded[file_name])} bytes')


Saving 1.02.+Multiple+linear+regression.csv to 1.02.+Multiple+linear+regression.csv
User uploaded file "1.02.+Multiple+linear+regression.csv" with length 1114 bytes


In [ ]:
df=pd.read_csv('1.02.+Multiple+linear+regression.csv')

In [ ]:
df.head()


SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [ ]:
model=LinearRegression()

In [ ]:
x=df[['SAT','Rand 1,2,3']]
y=df['GPA']




In [ ]:
model.fit(x,y)

LinearRegression()

In [ ]:
model.score(x,y)

0.4066811952814283

In [ ]:
model.coef_

array([ 0.00165354, -0.00826982])

In [ ]:
model.intercept_

0.29603261264909486

In [ ]:
model.predict([[750,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.52791914])

In [ ]:
adj_rsq=1-(1-model.score(x,y))*(len(y)-1)/(len(y)-x.shape[1]-1)
adj_rsq

0.3920313482513401

In [ ]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
scaler

StandardScaler()

In [ ]:
x_scaled=scaler.transform(x)

In [ ]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_scaled,y)

LinearRegression()

In [ ]:
model.coef_

array([ 0.17181389, -0.00703007])

In [ ]:
from google.colab import files

# Upload file
uploaded = files.upload()

# Check the uploaded files
for file_name in uploaded.keys():
    print(f'User uploaded file "{file_name}" with length {len(uploaded[file_name])} bytes')


Saving real_estate_price_size_year.csv to real_estate_price_size_year.csv
User uploaded file "real_estate_price_size_year.csv" with length 2409 bytes


In [ ]:
df=pd.read_csv('real_estate_price_size_year.csv')

In [ ]:
df.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [ ]:
x1=df[['size','year']]
y=df['price']

In [ ]:
model=LinearRegression()

In [ ]:
x1['size']

0      643.09
1      656.22
2      487.29
3     1504.75
4     1275.46
       ...   
95     549.80
96    1037.44
97    1504.75
98     648.29
99     705.29
Name: size, Length: 100, dtype: float64

In [ ]:
scaler.fit(x1)
X_scaled=scaler.transform(x1)

In [ ]:
model.fit(x_scaled,y)

ValueError: Found input variables with inconsistent numbers of samples: [84, 100]

In [ ]:
model.coef_

array([ 227.70085401, 2916.78532684])

In [ ]:
model.score(x,y)

0.7764803683276795

In [ ]:
adj_rsq=1-(1-model.score(x,y))*(len(y)-1)/(len(y)-x.shape[1]-1)

In [ ]:
adj_rsq

0.7718717161282502

In [ ]:
x

NameError: name 'x' is not defined